services:
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    volumes:
      -  C:\Users\inci4\Desktop\volumes\keycloak:/opt/keycloak/data

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - C:\Users\inci4\Desktop\volumes\mongodb:/data/db

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
      - 5432:5432
    volumes:
      - C:\Users\inci4\Desktop\volumes\postgres:/var/lib/postgresql/data

#  discovery-server:
#    build: ./discovery-server
#    ports:
#      - 8761:8761
#    environment:
#      - eureka.instance.prefer-ip-address= true
#    depends_on:
#      - keycloak

#  hotel-service:
#    build: ./hotel-service
#    ports:
#      - 3331:3331
#    environment:
#      - eureka.instance.prefer-ip-address=true
#      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
#      - spring.datasource.url=jdbc:postgresql://postgres:5432/hotel-service
#    depends_on:
#      - discovery-server
#      - postgres
#
#  api-gateway:
#    build: ./api-gateway
#    ports:
#      - 3333:3333
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    command: [ "./wait-for-it.sh", "hotel-service:3331" ]
#
#  rental-service:
#    build: ./rental-service
#    ports:
#      - 3332:3332
#    mem_limit: 700m
#    environment:
#      - eureka.instance.prefer-ip-address=true
#      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
#      - spring.datasource.url=jdbc:postgresql://postgres:5432/rental-service
#
#    depends_on:
#      - discovery-server
#      - postgres
#
#  customer-service:
#    build: ./customer-service
#    ports:
#      - 3330:3330
#    environment:
#      - eureka.instance.prefer-ip-address=true
#      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
#      - spring.data.mongodb.uri=mongodb://root:root@mongodb:27017/customer-service?authSource=admin